CREATE TABLE IF NOT EXISTS `m_mysqlindexer_index` (
		`final_id` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,	
		`document_id` int(11),
		`document_model` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
		`module` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
		`lang` char(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
		`searchbo` int(11),
		`searchfo` int(11),
		`document_accessor` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
		`document_ancestor` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,	
		`websiteids` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
		`label` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, 
		`text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci, 
		`aggregateText` text CHARACTER SET utf8 COLLATE utf8_unicode_ci, 
		`sortable_label` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, 
		`sortable_date` varchar(25) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, 
		`extras` text CHARACTER SET utf8 COLLATE utf8_unicode_ci, 		 
		PRIMARY KEY ( `final_id` ),
	    FULLTEXT KEY `TEXT` (`label`, `text`, `aggregateText`)
) ENGINE=MyISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;